### PR TITLE
Bump package versions for the official 1.2.0 release.

### PR DESCRIPTION
**Pull request by alexandesigner**
To become suitable for Meteor 1.7.0.1

### CODE REVIEW

**Comment by mitar** [comment]
Was there just a difference in version or is there also content change? Did anything changed in Tracker between previous and this version?

**Comment by alexandesigner** [comment]
Nice note @mitar

Actually there was a little "modernization" in the package, take a look at this commit https://github.com/meteor/meteor/commit/14f6f9328bf358b3d953968d29246573d2d05366#diff-a3f67d192b02bdb8822309c6f5a7b6bd

Let me know if you'd rather do it or I can just play to keep updating version properly.

**Comment by mitar** [comment]
So would you sync this package in a similar way?

**Comment by alexandesigner** [comment]
I'll take a look at this later, if there is any difficulty adapting then you help me.

You are more familiar with the changes 😊

**Comment by mitar** [comment]
Yea, check out. There are many changes, but structurally packages are the same.

**Comment by alexandesigner** [comment]
I think everything's working fine. Let me know if I can improve something

**Comment by mitar** [comment]
Just to comment that this has been integrated for quite some time now.

**Pull request closed without merging**
